config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  end
  resources :boggles do
  	resources :boggle_words, only: [:create]
    patch '/join' => 'boggles#join'
    patch '/finish' => 'boggles#finish'
  end
  get '/users' => 'users#index'
  post '/follow' => 'users#follow'
  post '/organize' => 'boggles#organize'
  get '/solve_boggle' => 'boggles#solve_boggle'
  post '/solve' => 'boggles#solve'

  root to: "boggles#new"

  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/boggle.rb
class Boggle < ApplicationRecord

	has_many :boggle_words, dependent: :destroy
	belongs_to :user, optional: true
	belongs_to :organizer, class_name: "User", optional: true
	has_many :boggle_players, dependent: :destroy
	has_many :players, through: :boggle_players, class_name: "User", foreign_key: :player_id

	validates_length_of :letters, minimum: 16, maximum: 16
	before_validation :generate_random_16

	scope :on_games, -> { where(finished: false) }
	scope :unfinished, -> { on_games }
	scope :latest, -> { where('created_at > ?', 1.day.ago) }

	accepts_nested_attributes_for :boggle_words

	def generate_random_16
		self.letters = better_sequence if self.letters.blank?
	end

	def combination_of_word_exists(word)
		#represent letters in 4 * 4 grid
		grid = generate_grid

		# check to see if first letter in the word exists in grid
		return false unless letters.include? word[0]


		# will be extending the combinations of letter in grid to form the word
		indexes = find_index(grid, word[0])

		extend_path(word, indexes, [], word[0])[0]
	end

	def extend_path(word, indexes, path=[], prefix)
		return prefix, path if prefix == word

		(indexes-path).each do |i|
			path << i

			first_index = i
			second_letter = word[prefix.length]

			is_neighbour, neighbour_indexes = is_neighbour(first_index, second_letter, path)

			
			if is_neighbour
				prefix += second_letter
				nav, path = extend_path(word, neighbour_indexes, path, prefix)
			end

			return word, path if nav == word
		end

		return false, path
	end

	def is_neighbour(first_index, second_letter, path)
		grid = @grid || generate_grid

		neighbour_indexes = get_neighbours_index(first_index)

		
		neighbour = false
		indexes = []

		neighbour_indexes.each { |n_i|
			if grid[n_i[0]][n_i[1]] == second_letter && !path.include?([n_i[0], n_i[1]])
				neighbour = true
				indexes << n_i
			end
		}

		return neighbour, indexes
	end

	def get_neighbours_index(indexes)
		neighbour_indexes = []
		i, j = indexes

		neighbour_indexes << [i-1, j] if i > 0				#left
		neighbour_indexes << [i+1, j] if i < 3				#right

		neighbour_indexes << [i, j-1] if j > 0				#down
		neighbour_indexes << [i-1, j-1] if j > 0 && i > 0	#down-left
		neighbour_indexes << [i+1, j-1] if j > 0 && i < 3	#down-right


		neighbour_indexes << [i, j+1] if j < 3 				# up
		neighbour_indexes << [i-1, j+1] if j < 3 && i > 0	#up-left
		neighbour_indexes << [i+1, j+1] if j < 3 && i < 3	#up-right

		neighbour_indexes
	end

	def solve_boggle(words=[], 
						str='',
						i=0,
						j=0,
						visited=[[false, false, false, false], [false, false, false, false], [false, false, false, false], [false, false, false, false]])
		

		if str.empty? || (!visited[i][j] && Trie::WORD_TRIE.children(str).present?)
			grid = generate_grid
		
			p 'condition met'
			p i, j
			
			visited[i][j] = true
			# visited.map {|v| p v}
			neighbour_indexes = get_neighbours_index([i, j])
			str += grid[i][j]
			words << str if Trie::WORD_TRIE.has_key?(str)

			neighbour_indexes.select{|mn| visited[mn[0]][mn[1]] == false }.each do |ij|
				p str
				p ij
				visited.map {|v| p v}
				i, j = ij
				solve_boggle(words, str, i, j, visited)
				visited[i][j] = false		
			end
		end

		p words
		words.uniq
	end

	def solve_for_all_position
		words = []
		(0..3).each do |i|
			(0..3).each do |j|
				visited=[[false, false, false, false], [false, false, false, false], [false, false, false, false], [false, false, false, false]]
				solve_boggle(words, '', i, j, visited)
			end
		end

		words.uniq
	end

	def find_index(grid, letter)
		indexes = []
		grid.each_with_index { |value, i|
			value.each_with_index { |val, j|
				indexes << [i, j] if val == letter
			}
		}

		indexes
	end

	def generate_grid
		grid = []
		for i in (1..4)
			grid << letters[i*4 - 4...i*4].split("")
		end

		@grid = grid
	end

	def four_letter_word(seed)
		datamuse_url = "https://api.datamuse.com/words?sp="

		# select a 4 letter word from datamuse api
		# use seed for randomness
		response = RestClient.get(datamuse_url + seed + '??')

		# select words with highest score, they are very common and simple
		body_sample = JSON.parse(response.body).first(5)
		word = body_sample.sample
		last_two = true

		# there can be case when there is no 4 letters word with those initials
		# instead opt for letters that starts and ends
		if !word
			last_two = false
			response = RestClient.get(datamuse_url + [seed.first, '?', '?', seed.last].join(''))
			# select words with highest score, they are very common and simple
			body_sample = JSON.parse(response.body).first(5)
			word = body_sample.sample
		end

		[word["word"], last_two]
	end

	def better_sequence
		# select 2 random seed letters
		seed = [1, 2].map {|i| ('a'...'q').to_a.sample}.join('')

		word, last_two = four_letter_word(seed)
		letters_array = word.split('')

		while letters_array.length < 16
		seed = letters_array.slice(letters_array.length - 4 , 2).join('')
		word, last_two = four_letter_word(seed)
		letters_array += last_two ? word.last(2).split("") : [word[1], word[2]]
		end

		p "THE COMBINATION: #{letters_array.join('')}"

		letters_array.join('')
	end

end

app/controllers/boggles_controller.rb
class BogglesController < ApplicationController
  before_action :set_boggle, only: [:show, :edit, :update, :destroy, :join, :finish]
  before_action :require_permission, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: :organize
  before_action :authenticate_user, only: [:index]

  include ActionView::Helpers::DateHelper

  # GET /boggles
  # GET /boggles.json
  def index
    @boggles = current_user.boggles.all
  end

  # GET /boggles/1
  # GET /boggles/1.json
  def show
    #render :edit
  end

  # GET /boggles/new
  def new
    @boggle = current_user.boggles.new if current_user.present?
    @boggle ||= Boggle.new
  end

  # GET /boggles/1/edit
  def edit
    set_match_id
  end

  # POST /boggles
  # POST /boggles.json
  def create
    @boggle = current_user.boggles.create(boggle_params) if current_user.present?
    @boggle ||= Boggle.new(boggle_params)

    respond_to do |format|
      if @boggle.save
        format.html {
          redirect_to edit_boggle_path(@boggle), notice: 'Boggle was successfully created.'
        }
        format.json { render :show, status: :created, location: @boggle }
      else
        format.html { render :new }
        format.json { render json: @boggle.errors, status: :unprocessable_entity }
      end
    end
  end

  def organize
    if current_user.organized_boggles.unfinished.present?
      flash[:alert] = 'Unfinished games are there, finish those before creating new'
      return redirect_to boggles_path
    end
    @boggle = current_user.organized_boggles.new

    respond_to do |format|
      if @boggle.save
        set_match_id if @boggle

        @boggle.boggle_players.create(player_id: current_user.id)
        format.html do
            ActionCable.server.broadcast 'boggle_game_channel',
                                         action: 'add-row',
                                         id:  @boggle.id,
                                         organizer: @boggle.organizer&.email || 'N/A',
                                         created_ago: time_ago_in_words(@boggle.created_at)

            redirect_back(fallback_location: root_path)
        end
      else
        format.html { render :new }
        format.json { render json: @boggle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boggles/1
  # PATCH/PUT /boggles/1.json
  def update
    respond_to do |format|
      if @boggle.update(boggle_params)
        format.html { redirect_to @boggle, notice: 'Boggle was successfully updated.' }
        format.json { render :show, status: :ok, location: @boggle }
      else
        format.html { render :edit }
        format.json { render json: @boggle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boggles/1
  # DELETE /boggles/1.json
  def destroy
    @boggle.destroy
    respond_to do |format|
      format.html { redirect_to boggles_url, notice: 'Boggle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def join
    @boggle.boggle_players.create(player_id: params[:player_id] || current_user.id )
    ActionCable.server.broadcast "match_channel_#{@boggle.id}",
                                 action: 'redirect-to',
                                 id:  @boggle.id

    respond_to do |f|
      f.js
      f.html { redirect_to edit_boggle_path(@boggle) }
    end
  end

  def finish
    if @boggle.organizer != current_user
      flash.now[:alert] = 'Only organizer can set finish to true'
    else
      flash.now[:notice] = 'Game on no more'
      @boggle.update(finished: true)

      ActionCable.server.broadcast 'boggle_game_channel',
                                   action: 'remove-row',
                                   id:  @boggle.id
    end
    redirect_to root_path
  end

  def solve_boggle
  end

  def solve
    @letters = params[:letters]
    if @letters.length != 16
      return redirect_to solve_boggle_path, alert: "Letters must be exactly 16 letters yours is #{@letters.length}"
    end
    boggle = Boggle.new(letters: @letters)
    @words = boggle.solve_for_all_position

    respond_to do |f|
      f.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boggle
      @boggle = Boggle.find_by_id(params[:id]) || Boggle.find(params[:boggle_id])
    end

    # Only allow a list of trusted parameters through.
    def boggle_params
      params.require(:boggle).permit(:finished, :begined_at)
    end

    def require_permission
      boggle = Boggle.find(params[:id])
      begin
        # cases when a user an access boggle
        # when boggle user and organizer is nil
        return true if boggle.organizer.nil?
        # when boggle players list contains current user's id
        return true if boggle.boggle_players.pluck(:player_id).include?(current_user.id) || boggle.organizer_id == current_user.id
        redirect_to root_path if current_user != boggle.user
      rescue
        flash[:alert] = "Permission Denied."
        redirect_to root_path
      end
    end

    def require_user
      return true if current_user.present?

      flash[:notice] = 'Login to organize a game.'
      redirect_to root_path if !current_user.present?
    end

    def authenticate_user
      redirect_to root_path unless current_user.present?
    end

    def set_match_id
      cookies[:match_id] = @boggle.id
    end
end

app/helpers/boggles_helper.rb
module BogglesHelper
end

app/views/boggles/_boggle_words.html.slim
- boggle_word = f.object
- klass = boggle_word.correct? ? 'green':'red'
h1[class=klass] = f.object.word

app/views/boggles/_form.html.slim
= form_for @boggle, url: {controller: 'boggles', action: 'organize'}, html: {class: 'new_boggle row justify-content-center'} do |f|
  - if @boggle.errors.any?
    #error_explanation
      h2 = "#{pluralize(@boggle.errors.count, "error")} prohibited this boggle from being saved:"
      ul
        - @boggle.errors.full_messages.each do |message|
          li = message

  = f.submit 'Play with others', class: 'actions btn btn-dark '

app/views/boggles/_games.html.slim
h3 List of Games

table.table
  thead
    tr
      th Game
      th Organizer
      th
      th
  tbody#game-body
    - (current_user&.subscribed_games&.unfinished&.latest&.order(created_at: :desc) + current_user.boggles&.unfinished.order(created_at: :desc)).uniq.each do |game|
      tr[id="boggle-row-#{game.id}"]
        td = game.id
        td = game&.organizer&.email
        td = time_ago_in_words(game.created_at)
        td
          = form_for game, url: boggle_join_path(game) do |f|
            = hidden_field_tag :player_id, current_user.id
            - joined = game.player_ids.include?(current_user.id)
            button.btn.btn-primary[disabled = joined]
              = joined ? 'JOINED' : 'JOIN'

app/views/boggles/edit.html.slim
.container
  .row.justify-content-md-center
    .col-12
      #boggle_words
        - if current_user.present?
          .span.border.border-success
            - player = BogglePlayer.find_by(boggle: @boggle, player: current_user)
            - player.boggle_words.correct.each do |boggle_word|
              span.badge.badge-success = boggle_word.word

          .span.border.border-danger
            - player.boggle_words.incorrect.each do |boggle_word|
              span.badge.badge-danger = boggle_word.word
        - else
          .span.border.border-success
            - @boggle.boggle_words.correct.each do |boggle_word|
              span.badge.badge-success = boggle_word.word
          .span.border.border-danger
            - @boggle.boggle_words.incorrect.each do |boggle_word|
              span.badge.badge-danger = boggle_word.word
      br

    - letters_array = @boggle.letters.split ''

    .row.justify-content-md-center[style="width: 100%"]
      .col-12.d-sm-block.d-none
        - if @boggle.boggle_players.blank?
          h6#score = "SCORE:" + @boggle.score.to_s
        - else
        - @boggle.boggle_players.each do |player|
          h6[id="score-#{player.player.id}" style="background-color: #{current_user.id == player.player.id ? 'green' : 'red'}; color: white"]= "SCORE #{player.player.id}:  " + player.score.to_s
      .col-md-9.col-sm-12
        #boggle_letters.my-3
          - (1..16).each do |i|
            - if @boggle.finished
              button.btn.btn-light.btn-outline-dark.boggle_letter[disabled] = letters_array[i-1]
            - else
              button.btn.btn-light.btn-outline-dark.boggle_letter = letters_array[i - 1]
            - if i % 4 == 0
              br
      .col-3.d-none.d-md-block
        - if @boggle.boggle_players.blank?
          h6#score = "SCORE:" + @boggle.score.to_s
        - else
          - @boggle.boggle_players.each do |player|
            h6[id="score-#{player.player.id}" style="background-color: #{current_user.id == player.player.id ? 'green':'red'}; color: white"]= "SCORE #{player.player.id}:  " + player.score.to_s

        - if current_user == @boggle.organizer && !@boggle.finished
          = form_tag boggle_path(@boggle), method: 'PATCH' do |f|
            = hidden_field_tag("boggle[finished]", true)
            button#finish.btn.btn-danger[type='submit'] Finish
      br
      br
  .row.justify-content-md-center
    = form_tag boggle_boggle_words_path(@boggle), remote: true do |f|
      .input-group
        = text_field_tag :word, '', autocomplete: :off, class: 'form-control', readonly: @boggle.finished?
        .input-group-append
          = submit_tag 'Push', class: 'btn btn-dark'


javascript:
  $('.boggle_letter').on('click', function () {
      let val = $('#word').val();
      if (typeof val !== 'undefined') {
          $('#word').val(val.toString() + $(this).text())
      }else {
          $('#word').val($(this).text())
      }
      $('#word').focus();
  });

  if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
      $('#word').attr('readonly', 'readonly')
  }

app/views/boggles/index.html.slim
h1 Listing boggles

table.table
  thead
    tr
      th ID
      th Total Correct Words
      th Total Attempted Words
      th Score
      th
      th
      th
      th

  tbody
    - @boggles.order(created_at: :desc).each do |boggle|
      tr
        td = boggle.id
        td = boggle.boggle_words.correct.count
        td = boggle.boggle_words.count
        td = boggle.score
        td = link_to 'Show', boggle
        td = !boggle.finished? ? link_to('Edit', edit_boggle_path(boggle)) : ''
        td = link_to 'Destroy', boggle, data: { confirm: 'Are you sure?' }, method: :delete
        td = !boggle.finished? ? link_to('Finish', boggle_finish_path(boggle), method: :patch) : ''

br

= link_to 'New Boggle', new_boggle_path

app/views/boggles/join.js.erb
window.location.replace("<%= edit_boggle_path(@boggle) %>")

app/views/boggles/new.html.slim
.container
  h1 New boggle
  .row.justify-content-center

    .col-5
      = render 'form'

    - if current_user.present?
      .col-7.d-block[style="height: 400px;overflow:scroll;"]
        = render 'games'

app/views/boggles/show.html.slim
p#notice = notice

.container
  .row.justify-content-md-center

    .col-12
      #boggle_words
        .span.border.border-success
          - @boggle.boggle_words.correct.each do |boggle_word|
            span.badge.badge-success = boggle_word.word

        .span.border.border-danger
          - @boggle.boggle_words.incorrect.each do |boggle_word|
            span.badge.badge-danger = boggle_word.word
      br

    - letters_array = @boggle.letters.split ''

    .row.justify-content-md-center
      .col-12
        #boggle_letters
          - (1..16).each do |i|
            button.btn.btn-light.btn-outline-dark.boggle_letter = letters_array[i-1]
            - if i % 4 == 0
              br

=< link_to 'Back', boggles_path

app/views/boggles/solve.js.erb
<% @words.each do |word| %>
    $("#boggle_words .span.border.border-success").append("<span class='badge badge-success'> <%= word %> </span>")
<% end %>

app/views/boggles/solve_boggle.html.slim
h1 Solve Boggle

= form_tag solve_path(format: :js), remote: true
    div.form-group
        label[for="letters"] = 'Letters'
        input[type="text" class="form-control" id="letters" name="letters"]

    button.btn.btn-primary[type="submit"]
        = 'Submit'

h2 Solutions

.container
    .row.justify-content-md-center

    .col-12
      #boggle_words
        .span.border.border-success