config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  end
  resources :boggles do
  	resources :boggle_words, only: [:create]
    patch '/join' => 'boggles#join'
    patch '/finish' => 'boggles#finish'
  end
  get '/users' => 'users#index'
  post '/follow' => 'users#follow'
  post '/organize' => 'boggles#organize'
  get '/solve_boggle' => 'boggles#solve_boggle'
  post '/solve' => 'boggles#solve'

  root to: "boggles#new"

  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoggleAssurance</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <a class="navbar-brand" href="/">Boggle</a>

      <div class="mx-auto">
        <%= form_for Boggle.new do |f| %>
          <%= f.hidden_field :begined_at %>
          <div class="">
            <%= button_tag "New game", type: 'button', class: 'btn btn-dark', id: 'play-boggle' %>
          </div>
        <% end %>
      </div>

      <div>
        <a href="/solve_boggle">SOLVE BOGGLE</a>
      </div>

      <div class="ml-auto">
        <% unless current_user.present? %>
          <button class="btn btn-danger">
            <%= link_to "Log In with Google", '/auth/google_oauth2', class: 'google-auth' %>
          </button>
        <% else %>
          <p><%= current_user.email %></p>
          <%= link_to "My Games", boggles_path, class: "btn btn-primary" %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
        <% end %>
      </div>
    </nav>
    <div id="message">
      <% if notice.present?%>
        <span class="border border-success">
          <%= notice %>
        </span>
      <% elsif alert.present?%>
        <span class="border border-danger">
          <%= alert%>
        </span>
      <% end %>
    </div>

    <%= yield %>
  <%= javascript_include_tag 'boggle-game' %>
  </body>
</html>